import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--Poppins",
});

const felixtitling = localFont({
  src: [
    {
      path: "/fonts/felix-titling/felixti.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--felixtitling",
  display: "swap",
});

export const metadata = {
  title: "HM Properties",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${felixtitling.variable} `}>
        {children}
      </body>
    </html>
  );
}
